# Generated by Django 5.0.2 on 2024-03-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_sensor_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='measurements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.measurement'),
        ),
    ]
